import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "var(--color-bg-primary)",
                foreground: "var(--color-text-primary)",
                accent: {
                    DEFAULT: "var(--color-accent)",
                    light: "var(--color-accent-light)",
                    dark: "var(--color-accent-dark)",
                    50: "var(--color-accent-50)",
                    100: "var(--color-accent-100)",
                    200: "var(--color-accent-200)",
                    300: "var(--color-accent-300)",
                    400: "var(--color-accent-400)",
                    500: "var(--color-accent-500)",
                    600: "var(--color-accent-600)",
                    700: "var(--color-accent-700)",
                    800: "var(--color-accent-800)",
                    900: "var(--color-accent-900)",
                },
                success: {
                    DEFAULT: "var(--color-success)",
                    light: "var(--color-success-light)",
                    dark: "var(--color-success-dark)",
                    50: "var(--color-success-50)",
                    500: "var(--color-success-500)",
                    600: "var(--color-success-600)",
                },
                link: {
                    DEFAULT: "var(--color-link)",
                    hover: "var(--color-link-hover)",
                    light: "var(--color-link-light)",
                    50: "var(--color-link-50)",
                    500: "var(--color-link-500)",
                    600: "var(--color-link-600)",
                },
                warning: {
                    DEFAULT: "var(--color-warning)",
                    light: "var(--color-warning-light)",
                    50: "var(--color-warning-50)",
                    500: "var(--color-warning-500)",
                    600: "var(--color-warning-600)",
                },
                error: {
                    DEFAULT: "var(--color-error)",
                    light: "var(--color-error-light)",
                    50: "var(--color-error-50)",
                    500: "var(--color-error-500)",
                    600: "var(--color-error-600)",
                },
                nav: {
                    purple: "var(--color-nav-purple)",
                    "purple-light": "var(--color-nav-purple-light)",
                    cyan: "var(--color-nav-cyan)",
                    "cyan-light": "var(--color-nav-cyan-light)",
                    green: "var(--color-nav-green)",
                    "green-light": "var(--color-nav-green-light)",
                },
                terminal: {
                    prompt: "var(--color-terminal-prompt)",
                    cursor: "var(--color-terminal-cursor)",
                    comment: "var(--color-terminal-comment)",
                },
                mac: {
                    red: "var(--color-mac-red)",
                    yellow: "var(--color-mac-yellow)",
                    green: "var(--color-mac-green)",
                },
                gray: {
                    50: "var(--color-gray-50)",
                    100: "var(--color-gray-100)",
                    200: "var(--color-gray-200)",
                    300: "var(--color-gray-300)",
                    400: "var(--color-gray-400)",
                    500: "var(--color-gray-500)",
                    600: "var(--color-gray-600)",
                    700: "var(--color-gray-700)",
                    800: "var(--color-gray-800)",
                    900: "var(--color-gray-900)",
                },
                // ============================================
                // 手绘风格设计系统 - 颜色
                // ============================================
                'sketch-paper': {
                    white: '#FAFAF8',
                    cream: '#F5F1E8',
                    aged: '#EDE8D0',
                    kraft: '#C4A77D',
                    graph: '#F0F4F0',
                },
                'sketch-pencil': {
                    light: '#9CA3AF',
                    medium: '#6B7280',
                    dark: '#4A4A4A',
                },
                'sketch-ink': {
                    black: '#1A1A1A',
                    charcoal: '#2D2D2D',
                },
                'sketch-crayon': {
                    red: '#E85D4E',
                    orange: '#F4A261',
                    yellow: '#E9C46A',
                    green: '#2A9D8F',
                    blue: '#4A90E2',
                    purple: '#9B59B6',
                    pink: '#E87EA1',
                },
                'sketch': {
                    primary: '#4A90E2',
                    secondary: '#9B59B6',
                    success: '#2A9D8F',
                    warning: '#E9C46A',
                    error: '#E85D4E',
                    background: '#FAFAF8',
                    surface: '#F5F1E8',
                    text: '#1A1A1A',
                    'text-muted': '#6B7280',
                    border: '#9CA3AF',
                },
            },
            spacing: {
                'token-0': "var(--space-0)",
                'token-px': "var(--space-px)",
                'token-0-5': "var(--space-0-5)",
                'token-xs': "var(--space-xs)",
                'token-sm': "var(--space-sm)",
                'token-md': "var(--space-md)",
                'token-lg': "var(--space-lg)",
                'token-xl': "var(--space-xl)",
                'token-2xl': "var(--space-2xl)",
                'token-3xl': "var(--space-3xl)",
                'token-4xl': "var(--space-4xl)",
                'token-5xl': "var(--space-5xl)",
                'token-section': "var(--space-section)",
                'token-card': "var(--space-card-padding)",
                'token-card-sm': "var(--space-card-padding-sm)",
                'token-header': "var(--space-header-height)",
                'token-gap': "var(--space-gap)",
                'token-gap-sm': "var(--space-gap-sm)",
                'token-gap-lg': "var(--space-gap-lg)",
                // 手绘风格间距
                'sketch-0': '0',
                'sketch-px': '1px',
                'sketch-xs': '0.25rem',
                'sketch-sm': '0.5rem',
                'sketch-md': '1rem',
                'sketch-lg': '1.5rem',
                'sketch-xl': '2.5rem',
                'sketch-2xl': '4rem',
                'sketch-3xl': '6rem',
            },
            maxWidth: {
                'token-sm': "var(--container-sm)",
                'token-md': "var(--container-md)",
                'token-lg': "var(--container-lg)",
                'token-xl': "var(--container-xl)",
                'token-2xl': "var(--container-2xl)",
                'token-content': "var(--container-content)",
                'token-wide': "var(--container-wide)",
            },
            borderRadius: {
                'token-none': "var(--radius-none)",
                'token-sm': "var(--radius-sm)",
                'token-md': "var(--radius-md)",
                'token-lg': "var(--radius-lg)",
                'token-xl': "var(--radius-xl)",
                'token-2xl': "var(--radius-2xl)",
                'token-3xl': "var(--radius-3xl)",
                'token-full': "var(--radius-full)",
                'token-button': "var(--radius-button)",
                'token-card': "var(--radius-card)",
                'token-input': "var(--radius-input)",
                'token-badge': "var(--radius-badge)",
                // 手绘风格圆角
                'sketch-none': '0',
                'sketch-sm': '4px',
                'sketch-md': '8px',
                'sketch-lg': '12px',
                'sketch-xl': '16px',
                'sketch-full': '9999px',
                'sketch-organic': '255px 15px 225px 15px / 15px 225px 15px 255px',
                'sketch-organic-sm': '12px 15px 14px 16px / 16px 14px 15px 12px',
            },
            boxShadow: {
                'token-none': "var(--shadow-none)",
                'token-sm': "var(--shadow-sm)",
                'token-md': "var(--shadow-md)",
                'token-lg': "var(--shadow-lg)",
                'token-xl': "var(--shadow-xl)",
                'token-2xl': "var(--shadow-2xl)",
                'token-card': "var(--shadow-card)",
                'token-card-hover': "var(--shadow-card-hover)",
                'token-header': "var(--shadow-header)",
                'token-button': "var(--shadow-button)",
                // 手绘风格阴影
                'sketch-none': 'none',
                'sketch-sm': '1px 2px 0 0 rgba(0, 0, 0, 0.05)',
                'sketch-md': '2px 3px 0 0 rgba(0, 0, 0, 0.08)',
                'sketch-lg': '3px 4px 0 0 rgba(0, 0, 0, 0.1), 4px 5px 0 0 rgba(0, 0, 0, 0.05)',
                'sketch-xl': '4px 6px 0 0 rgba(0, 0, 0, 0.1), 5px 7px 0 0 rgba(0, 0, 0, 0.08), 6px 8px 0 0 rgba(0, 0, 0, 0.05)',
                'sketch': '3px 4px 0 0 rgba(0, 0, 0, 0.1), 4px 5px 0 0 rgba(0, 0, 0, 0.08), 5px 6px 0 0 rgba(0, 0, 0, 0.05)',
            },
            transitionDuration: {
                'token-fast': "var(--transition-fast)",
                'token-normal': "var(--transition-normal)",
                'token-slow': "var(--transition-slow)",
                // 手绘风格过渡
                'sketch-fast': '150ms',
                'sketch-normal': '200ms',
                'sketch-slow': '300ms',
            },
            transitionTimingFunction: {
                'token-default': "var(--ease-default)",
                'token-in': "var(--ease-in)",
                'token-out': "var(--ease-out)",
                'token-in-out': "var(--ease-in-out)",
                // 手绘风格缓动
                'sketch-default': 'cubic-bezier(0.4, 0, 0.2, 1)',
                'sketch-in': 'cubic-bezier(0.4, 0, 1, 1)',
                'sketch-out': 'cubic-bezier(0, 0, 0.2, 1)',
                'sketch-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
                'sketch-bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
            },
            fontFamily: {
                mono: ["var(--font-mono)", "monospace"],
                sans: ["var(--font-sans)", "sans-serif"],
                // 手绘风格字体
                'sketch-heading': ['Caveat', 'cursive'],
                'sketch-subheading': ['Patrick Hand', 'cursive'],
                'sketch-body': ['Quicksand', 'sans-serif'],
                'sketch-accent': ['Indie Flower', 'cursive'],
                'sketch-code': ['Kalam', 'cursive'],
            },
            fontSize: {
                'token-xs': "var(--font-size-xs)",
                'token-sm': "var(--font-size-sm)",
                'token-base': "var(--font-size-base)",
                'token-lg': "var(--font-size-lg)",
                'token-xl': "var(--font-size-xl)",
                'token-2xl': "var(--font-size-2xl)",
                'token-3xl': "var(--font-size-3xl)",
                'token-4xl': "var(--font-size-4xl)",
                'token-5xl': "var(--font-size-5xl)",
                'token-6xl': "var(--font-size-6xl)",
                // 手绘风格字体大小
                'sketch-xs': ['0.75rem', { lineHeight: '1.5' }],
                'sketch-sm': ['0.875rem', { lineHeight: '1.6' }],
                'sketch-base': ['1rem', { lineHeight: '1.7' }],
                'sketch-lg': ['1.125rem', { lineHeight: '1.7' }],
                'sketch-xl': ['1.25rem', { lineHeight: '1.5' }],
                'sketch-2xl': ['1.5rem', { lineHeight: '1.4' }],
                'sketch-3xl': ['1.75rem', { lineHeight: '1.4' }],
                'sketch-4xl': ['2.25rem', { lineHeight: '1.3' }],
                'sketch-5xl': ['3rem', { lineHeight: '1.2' }],
                'sketch-6xl': ['4rem', { lineHeight: '1.1' }],
            },
            lineHeight: {
                'token-none': "var(--line-height-none)",
                'token-tight': "var(--line-height-tight)",
                'token-snug': "var(--line-height-snug)",
                'token-normal': "var(--line-height-normal)",
                'token-relaxed': "var(--line-height-relaxed)",
                'token-loose': "var(--line-height-loose)",
                // 手绘风格行高
                'sketch-none': '1',
                'sketch-tight': '1.25',
                'sketch-snug': '1.375',
                'sketch-normal': '1.5',
                'sketch-relaxed': '1.625',
                'sketch-loose': '1.75',
            },
            fontWeight: {
                'token-light': "var(--font-weight-light)",
                'token-normal': "var(--font-weight-normal)",
                'token-medium': "var(--font-weight-medium)",
                'token-semibold': "var(--font-weight-semibold)",
                'token-bold': "var(--font-weight-bold)",
            },
            letterSpacing: {
                'token-tighter': "var(--letter-spacing-tighter)",
                'token-tight': "var(--letter-spacing-tight)",
                'token-normal': "var(--letter-spacing-normal)",
                'token-wide': "var(--letter-spacing-wide)",
                'token-wider': "var(--letter-spacing-wider)",
                // 手绘风格字间距
                'sketch-tighter': '-0.05em',
                'sketch-tight': '-0.025em',
                'sketch-normal': '0',
                'sketch-wide': '0.025em',
                'sketch-wider': '0.05em',
            },
            zIndex: {
                'token-dropdown': "var(--z-index-dropdown)",
                'token-sticky': "var(--z-index-sticky)",
                'token-fixed': "var(--z-index-fixed)",
                'token-modal-backdrop': "var(--z-index-modal-backdrop)",
                'token-modal': "var(--z-index-modal)",
                'token-popover': "var(--z-index-popover)",
                'token-tooltip': "var(--z-index-tooltip)",
                'token-toast': "var(--z-index-toast)",
                // 手绘风格 z-index
                'sketch-dropdown': '1000',
                'sketch-sticky': '1020',
                'sketch-fixed': '1030',
                'sketch-modal-backdrop': '1040',
                'sketch-modal': '1050',
                'sketch-popover': '1060',
                'sketch-tooltip': '1070',
                'sketch-toast': '1080',
            },
            rotate: {
                // 手绘风格旋转
                'sketch-left': '-1deg',
                'sketch-right': '1deg',
                'sketch-left-md': '-2deg',
                'sketch-right-md': '2deg',
            },
            borderWidth: {
                // 手绘风格边框
                'sketch-thin': '1px',
                'sketch-normal': '2px',
                'sketch-thick': '3px',
            },
            keyframes: {
                // 手绘风格动画
                'sketch-wiggle': {
                    '0%, 100%': { transform: 'rotate(-1deg)' },
                    '50%': { transform: 'rotate(1deg)' },
                },
                'sketch-bounce': {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-4px)' },
                },
                'sketch-shake': {
                    '0%, 100%': { transform: 'translateX(0)' },
                    '25%': { transform: 'translateX(-2px)' },
                    '75%': { transform: 'translateX(2px)' },
                },
            },
            animation: {
                'sketch-wiggle': 'sketch-wiggle 0.3s ease-in-out',
                'sketch-bounce': 'sketch-bounce 0.4s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
                'sketch-shake': 'sketch-shake 0.3s ease-in-out',
            },
            backgroundImage: {
                // 手绘风格背景
                'sketch-graph': 'linear-gradient(#e5e7eb 1px, transparent 1px), linear-gradient(90deg, #e5e7eb 1px, transparent 1px)',
                'sketch-lined': 'repeating-linear-gradient(transparent, transparent 31px, #e5e7eb 31px, #e5e7eb 32px)',
                'sketch-dot': 'radial-gradient(#e5e7eb 1px, transparent 1px)',
                'sketch-highlight': 'linear-gradient(transparent 60%, rgba(233, 196, 106, 0.4) 60%)',
            },
            backgroundSize: {
                'sketch-graph': '20px 20px',
                'sketch-lined': '100% 32px',
                'sketch-dot': '20px 20px',
            },
            typography: {
                DEFAULT: {
                    css: {
                        color: "var(--foreground)",
                        a: {
                            color: "inherit",
                            textDecoration: "underline",
                            transition: "opacity 0.2s",
                            "&:hover": {
                                opacity: 0.7,
                            },
                        },
                        'h1, h2, h3, h4, h5, h6': {
                            fontFamily: "var(--font-mono)",
                            color: "var(--foreground)",
                            fontWeight: "600"
                        },
                        code: {
                            color: "var(--color-accent)",
                            backgroundColor: "rgba(0,0,0,0.05)",
                            padding: "0.2rem 0.4rem",
                            borderRadius: "var(--radius-md)",
                        },
                        'code::before': {
                            content: '""',
                        },
                        'code::after': {
                            content: '""',
                        },
                    },
                },
            },
        },
    },
    plugins: [require("@tailwindcss/typography")],
};
export default config;
